services:
  backend:
    profiles:
      - prod
    build:
      context: back-end
      dockerfile: Dockerfile
    container_name: nlt-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/database_nlt
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app_net

  frontend:
    profiles:
      - prod
    build:
      context: front-end
      dockerfile: Dockerfile
    container_name: nlt-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_net

  rabbitmq:
    image: rabbitmq:latest
    container_name: nlt-rabbitmq
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  celery_worker:
    build:
      context: back-end
      dockerfile: Dockerfile
    container_name: nlt-celery-worker
    command: celery -A src.celery_app.celery_app worker --loglevel=info
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_net

  postgres:
    image: postgres:16-alpine
    container_name: nlt-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_nlt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
